/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;
import com.core.farmacia.panel.cliente.panelCliente;
import com.core.farmacia.panel.compra.panelCompra;
import com.core.farmacia.panel.proveedor.panelProveedor;
import com.core.farmacia.panel.inventario.panelInventario;
import com.core.farmacia.panel.venta.panelVenta;
import paneles.CambiaPanel;


/**
 *
 * @author edin-
 */
public class prinPnl extends javax.swing.JFrame {

    /**
     * Creates new form prinP
     */
    int posicion;
    public prinPnl() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pnlboton = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 460));

        pnlboton.setBackground(new java.awt.Color(0, 18, 50));
        pnlboton.setPreferredSize(new java.awt.Dimension(140, 79));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlbotonLayout = new javax.swing.GroupLayout(pnlboton);
        pnlboton.setLayout(pnlbotonLayout);
        pnlbotonLayout.setHorizontalGroup(
            pnlbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbotonLayout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlbotonLayout.setVerticalGroup(
            pnlbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pnlboton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 794, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlboton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setBackground(new java.awt.Color(0, 18, 50));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btCompra1.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btCompra2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnVenta1.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnVenta2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlMenu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btInventario.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btInventario2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnProveedor1.png"))); // NOI18N
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnProveedor2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 140, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCliente1.png"))); // NOI18N
        jButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCliente2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnlMenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 140, 50));

        getContentPane().add(pnlMenu, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.LINE_END);

        pnlPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      posicion = pnlMenu.getX();
        // int posicionP=pnlPrincipal.getX();
        //pnlMenu.setBounds(10, 59, 180, 520);

        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlMenu);
            Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlboton);
            //Animacion.Animacion.mover_izquierda(190, 60, 2, 2, pnlPrincipal);
            // pnlMenu.setBounds(10, 59, 60, 520);

        } else {

            Animacion.Animacion.mover_derecha(-80, 0, 2, 2, pnlMenu);
             Animacion.Animacion.mover_derecha(-80, 0, 2, 2, pnlboton);
           // Animacion.Animacion.mover_derecha(60, 190, 2, 2, pnlPrincipal);
            // pnlMenu.setBounds(10, 59, 180, 520);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CambiaPanel(pnlPrincipal, new panelCompra());
         posicion = pnlMenu.getX();
        if(posicion!=-80){
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlMenu);
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlboton);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new CambiaPanel(pnlPrincipal, new panelInventario());
        posicion = pnlMenu.getX();
        if(posicion!=-80){
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlMenu);
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlboton);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         new CambiaPanel(pnlPrincipal, new panelCliente());
          posicion = pnlMenu.getX();
        if(posicion!=-80){
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlMenu);
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlboton);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       new CambiaPanel(pnlPrincipal, new panelProveedor());
         posicion = pnlMenu.getX();
        if(posicion!=-80){
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlMenu);
             Animacion.Animacion.mover_izquierda(0, -80, 2, 2, pnlboton);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prinPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prinPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prinPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prinPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prinPnl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlboton;
    // End of variables declaration//GEN-END:variables
}
