/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import paneles.CambiaPanel;

/**
 *
 * @author edin-
 */
public class prinP extends javax.swing.JFrame {

    /**
     * Creates new form prinP
     */
     public AnimationClass ac= new AnimationClass();
    public prinP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        titleTablero = new javax.swing.JLabel();
        jCTextField1 = new app.bolivia.swing.JCTextField();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tres = new rsbuttom.RSButtonMetro();
        dos = new rsbuttom.RSButtonMetro();
        cinco = new rsbuttom.RSButtonMetro();
        seis = new rsbuttom.RSButtonMetro();
        uno = new rsbuttom.RSButtonMetro();
        cuatro = new rsbuttom.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 33, -1));

        titleTablero.setBackground(new java.awt.Color(255, 255, 255));
        titleTablero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleTablero.setForeground(new java.awt.Color(255, 255, 255));
        titleTablero.setText("Dashboard - RojeruSan");
        jPanel2.add(titleTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 11, -1, 41));

        jCTextField1.setBackground(new java.awt.Color(38, 86, 186));
        jCTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCTextField1.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField1.setPlaceholder("SEARCH");
        jCTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, 281, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));
        pnlMenu.setAlignmentX(0.0F);
        pnlMenu.setAlignmentY(0.0F);
        pnlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMenu.setPreferredSize(new java.awt.Dimension(174, 515));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(239, 238, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("ESCUELA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 6, -1, -1));

        tres.setBackground(new java.awt.Color(239, 238, 244));
        tres.setForeground(new java.awt.Color(128, 128, 131));
        tres.setText("Alumnos");
        tres.setColorHover(new java.awt.Color(204, 204, 204));
        tres.setColorNormal(new java.awt.Color(239, 238, 244));
        tres.setColorPressed(new java.awt.Color(204, 204, 204));
        tres.setColorTextHover(new java.awt.Color(128, 128, 131));
        tres.setColorTextNormal(new java.awt.Color(128, 128, 131));
        tres.setColorTextPressed(new java.awt.Color(128, 128, 131));
        tres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tres.setIconTextGap(19);
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tresMousePressed(evt);
            }
        });
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        pnlMenu.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 50));

        dos.setBackground(new java.awt.Color(239, 238, 244));
        dos.setForeground(new java.awt.Color(128, 128, 131));
        dos.setText("Venta");
        dos.setColorHover(new java.awt.Color(204, 204, 204));
        dos.setColorNormal(new java.awt.Color(239, 238, 244));
        dos.setColorPressed(new java.awt.Color(204, 204, 204));
        dos.setColorTextHover(new java.awt.Color(128, 128, 131));
        dos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        dos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        dos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dos.setIconTextGap(25);
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dosMousePressed(evt);
            }
        });
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        pnlMenu.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 50));

        cinco.setBackground(new java.awt.Color(239, 238, 244));
        cinco.setForeground(new java.awt.Color(128, 128, 131));
        cinco.setText("Asignaturas");
        cinco.setColorHover(new java.awt.Color(204, 204, 204));
        cinco.setColorNormal(new java.awt.Color(239, 238, 244));
        cinco.setColorPressed(new java.awt.Color(204, 204, 204));
        cinco.setColorTextHover(new java.awt.Color(128, 128, 131));
        cinco.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cinco.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cinco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cinco.setIconTextGap(19);
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cincoMousePressed(evt);
            }
        });
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        pnlMenu.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 50));

        seis.setBackground(new java.awt.Color(239, 238, 244));
        seis.setForeground(new java.awt.Color(128, 128, 131));
        seis.setText("Acerca de");
        seis.setColorHover(new java.awt.Color(204, 204, 204));
        seis.setColorNormal(new java.awt.Color(239, 238, 244));
        seis.setColorPressed(new java.awt.Color(204, 204, 204));
        seis.setColorTextHover(new java.awt.Color(128, 128, 131));
        seis.setColorTextNormal(new java.awt.Color(128, 128, 131));
        seis.setColorTextPressed(new java.awt.Color(128, 128, 131));
        seis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        seis.setIconTextGap(25);
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seisMousePressed(evt);
            }
        });
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        pnlMenu.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, 50));

        uno.setForeground(new java.awt.Color(128, 128, 131));
        uno.setText("Inicio");
        uno.setColorHover(new java.awt.Color(204, 204, 204));
        uno.setColorNormal(new java.awt.Color(204, 204, 204));
        uno.setColorPressed(new java.awt.Color(204, 204, 204));
        uno.setColorTextHover(new java.awt.Color(128, 128, 131));
        uno.setColorTextNormal(new java.awt.Color(128, 128, 131));
        uno.setColorTextPressed(new java.awt.Color(128, 128, 131));
        uno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        uno.setIconTextGap(25);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        pnlMenu.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 50));

        cuatro.setBackground(new java.awt.Color(239, 238, 244));
        cuatro.setForeground(new java.awt.Color(128, 128, 131));
        cuatro.setText("Profesores");
        cuatro.setColorHover(new java.awt.Color(204, 204, 204));
        cuatro.setColorNormal(new java.awt.Color(239, 238, 244));
        cuatro.setColorPressed(new java.awt.Color(204, 204, 204));
        cuatro.setColorTextHover(new java.awt.Color(128, 128, 131));
        cuatro.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cuatro.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cuatro.setIconTextGap(19);
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatroMousePressed(evt);
            }
        });
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        pnlMenu.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 50));
        pnlMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Venta.png"))); // NOI18N
        pnlMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra.png"))); // NOI18N
        pnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chat.png"))); // NOI18N
        pnlMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/xd (1).png"))); // NOI18N
        pnlMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente (1).png"))); // NOI18N
        pnlMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta2.png"))); // NOI18N
        pnlMenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 570));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setAlignmentX(0.0F);
        pnlPrincipal.setAlignmentY(0.0F);
        pnlPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 870, 484));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 70));
        jLabel2.getAccessibleContext().setAccessibleParent(uno);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // new CambiaPanel(pnlMenu, new paneles.pnMenu());
        
        int posicion = pnlMenu.getX();
        int posicionP=pnlPrincipal.getX();
         
      
       
         //pnlMenu.setBounds(10, 59, 180, 520);
         
        if (posicion > -1) {
             
           
            Animacion.Animacion.mover_izquierda(0, -110, 2, 2, pnlMenu);
           // Animacion.Animacion.mover_izquierda(0, 0, 2, 2, pnlPrincipal);
           // pnlMenu.setBounds(10, 59, 60, 520);
            
        } else {
          
            Animacion.Animacion.mover_derecha(0, 0, 2, 2, pnlMenu);
            //Animacion.Animacion.mover_derecha(0, 0, 2, 2, pnlPrincipal);
            // pnlMenu.setBounds(10, 59, 180, 520);

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField1ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //Point mueve = MouseInfo.getPointerInfo().getLocation();
       // this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        //x = evt.getX();
       // y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void tresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(true);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
    }//GEN-LAST:event_tresMousePressed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed

         Animacion.Animacion.mover_izquierda(0, -110, 2, 2, pnlMenu);
        if (this.tres.isSelected()) {
             new CambiaPanel(pnlPrincipal, new paneles.pnCompra());
            this.tres.setColorNormal(new Color(204, 204, 204));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));

            this.uno.setColorNormal(new Color(239, 238, 244));
            this.uno.setColorHover(new Color(204, 204, 204));
            this.uno.setColorPressed(new Color(204, 204, 204));

            this.dos.setColorNormal(new Color(239, 238, 244));
            this.dos.setColorHover(new Color(204, 204, 204));
            this.dos.setColorPressed(new Color(204, 204, 204));

            this.cuatro.setColorNormal(new Color(239, 238, 244));
            this.cuatro.setColorHover(new Color(204, 204, 204));
            this.cuatro.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.seis.setColorNormal(new Color(239, 238, 244));
            this.seis.setColorHover(new Color(204, 204, 204));
            this.seis.setColorPressed(new Color(204, 204, 204));
        } else {
            this.tres.setColorNormal(new Color(239, 238, 244));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tresActionPerformed

    private void dosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(true);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
    }//GEN-LAST:event_dosMousePressed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed

        Animacion.Animacion.mover_izquierda(0, -110, 2, 2, pnlMenu);
        
        if (this.dos.isSelected()) {
             new CambiaPanel(pnlPrincipal, new paneles.pnVenta());
            this.dos.setColorNormal(new Color(204, 204, 204));
            this.dos.setColorHover(new Color(204, 204, 204));
            this.dos.setColorPressed(new Color(204, 204, 204));

            this.uno.setColorNormal(new Color(239, 238, 244));
            this.uno.setColorHover(new Color(204, 204, 204));
            this.uno.setColorPressed(new Color(204, 204, 204));

            this.tres.setColorNormal(new Color(239, 238, 244));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));

            this.cuatro.setColorNormal(new Color(239, 238, 244));
            this.cuatro.setColorHover(new Color(204, 204, 204));
            this.cuatro.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.seis.setColorNormal(new Color(239, 238, 244));
            this.seis.setColorHover(new Color(204, 204, 204));
            this.seis.setColorPressed(new Color(204, 204, 204));

        } else {
            this.dos.setColorNormal(new Color(239, 238, 244));
            this.dos.setColorHover(new Color(204, 204, 204));
            this.dos.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_dosActionPerformed

    private void cincoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(true);
        this.seis.setSelected(false);
    }//GEN-LAST:event_cincoMousePressed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // tablero.setText("ASIGNATURAS");
       Animacion.Animacion.mover_izquierda(0, -110, 2, 2, pnlMenu);
        if (this.cinco.isSelected()) {
               new CambiaPanel(pnlPrincipal, new paneles.pnCliente());
            this.uno.setColorNormal(new Color(239, 238, 244));
            this.uno.setColorHover(new Color(204, 204, 204));
            this.uno.setColorPressed(new Color(204, 204, 204));

            this.dos.setColorNormal(new Color(239, 238, 244));
            this.dos.setColorHover(new Color(204, 204, 204));
            this.dos.setColorPressed(new Color(204, 204, 204));

            this.tres.setColorNormal(new Color(239, 238, 244));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));

            this.cuatro.setColorNormal(new Color(239, 238, 244));
            this.cuatro.setColorHover(new Color(204, 204, 204));
            this.cuatro.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(204, 204, 204));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.seis.setColorNormal(new Color(239, 238, 244));
            this.seis.setColorHover(new Color(204, 204, 204));
            this.seis.setColorPressed(new Color(204, 204, 204));

        } else {
            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void seisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(true);
    }//GEN-LAST:event_seisMousePressed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        //  tablero.setText("ACERCA DE");
         Animacion.Animacion.mover_izquierda(0, -110, 2, 2, pnlMenu);
        if (this.seis.isSelected()) {
             new CambiaPanel(pnlPrincipal, new paneles.pnServicios());
            this.uno.setColorNormal(new Color(239, 238, 244));
            this.uno.setColorHover(new Color(204, 204, 204));
            this.uno.setColorPressed(new Color(204, 204, 204));

            this.dos.setColorNormal(new Color(239, 238, 244));
            this.dos.setColorHover(new Color(204, 204, 204));
            this.dos.setColorPressed(new Color(204, 204, 204));

            this.tres.setColorNormal(new Color(239, 238, 244));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));

            this.cuatro.setColorNormal(new Color(239, 238, 244));
            this.cuatro.setColorHover(new Color(204, 204, 204));
            this.cuatro.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.seis.setColorNormal(new Color(204, 204, 204));
            this.seis.setColorHover(new Color(204, 204, 204));
            this.seis.setColorPressed(new Color(204, 204, 204));

        } else {
            this.seis.setColorNormal(new Color(239, 238, 244));
            this.seis.setColorHover(new Color(204, 204, 204));
            this.seis.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_seisActionPerformed

    private void cuatroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(true);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
    }//GEN-LAST:event_cuatroMousePressed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        //tablero.setText("PROFESORES");
          Animacion.Animacion.mover_izquierda(0, -110, 2, 2, pnlMenu);
        if (this.cuatro.isSelected()) {
            new CambiaPanel(pnlPrincipal, new paneles.pnProveedor());
            this.uno.setColorNormal(new Color(239, 238, 244));
            this.uno.setColorHover(new Color(204, 204, 204));
            this.uno.setColorPressed(new Color(204, 204, 204));

            this.dos.setColorNormal(new Color(239, 238, 244));
            this.dos.setColorHover(new Color(204, 204, 204));
            this.dos.setColorPressed(new Color(204, 204, 204));

            this.tres.setColorNormal(new Color(239, 238, 244));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));

            this.cuatro.setColorNormal(new Color(204, 204, 204));
            this.cuatro.setColorHover(new Color(204, 204, 204));
            this.cuatro.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.seis.setColorNormal(new Color(239, 238, 244));
            this.seis.setColorHover(new Color(204, 204, 204));
            this.seis.setColorPressed(new Color(204, 204, 204));

        } else {
            this.cuatro.setColorNormal(new Color(239, 238, 244));
            this.cuatro.setColorHover(new Color(204, 204, 204));
            this.cuatro.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
          Animacion.Animacion.mover_izquierda(0, -110, 2, 2, pnlMenu);
        new CambiaPanel(pnlPrincipal, new paneles.pnInventario());
         if (this.uno.isSelected()) {
              
            this.uno.setColorNormal(new Color(204, 204, 204));
            this.uno.setColorHover(new Color(204, 204, 204));
            this.uno.setColorPressed(new Color(204, 204, 204));

            this.dos.setColorNormal(new Color(239, 238, 244));
            this.dos.setColorHover(new Color(204, 204, 204));
            this.dos.setColorPressed(new Color(204, 204, 204));

            this.tres.setColorNormal(new Color(239, 238, 244));
            this.tres.setColorHover(new Color(204, 204, 204));
            this.tres.setColorPressed(new Color(204, 204, 204));

            this.cuatro.setColorNormal(new Color(239, 238, 244));
            this.cuatro.setColorHover(new Color(204, 204, 204));
            this.cuatro.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.seis.setColorNormal(new Color(239, 238, 244));
            this.seis.setColorHover(new Color(204, 204, 204));
            this.seis.setColorPressed(new Color(204, 204, 204));

        } else {
            this.uno.setColorNormal(new Color(239, 238, 244));
            this.uno.setColorHover(new Color(204, 204, 204));
            this.uno.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_unoActionPerformed

    /**
     * @param args the command line arguments
      */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    
    //quitar
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prinP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prinP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prinP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prinP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prinP().setVisible(true);
            }
        });
    }   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro cinco;
    private rsbuttom.RSButtonMetro cuatro;
    private rsbuttom.RSButtonMetro dos;
    private javax.swing.JButton jButton1;
    private app.bolivia.swing.JCTextField jCTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private rsbuttom.RSButtonMetro seis;
    private javax.swing.JLabel titleTablero;
    private rsbuttom.RSButtonMetro tres;
    private rsbuttom.RSButtonMetro uno;
    // End of variables declaration//GEN-END:variables
}
