/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.core.farmacia.mysql;
/*
import com.core.farmacia.dao.DAOCompra;
import com.core.farmacia.dao.DAOException;
import com.core.farmacia.dao.DAOManager;
import com.core.farmacia.model.Compra;
import com.core.farmacia.model.LineaProducto;
import com.core.farmacia.model.Proveedor;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
*/
/*
/**
 *
 * @author nuevo
 */
/*
public class CompraMysqlDaoImpl implements DAOCompra {

    private String INSERT = "INSERT INTO compra(id_proveedor, nro_factura, fecha, hora) VALUES(?,?,current_date(), current_time())";
    private String DELETE = "DELETE FROM compra WHERE id = ?";
    private String UPDATE = "UPDATE compra SET id_proveedor = ?, nro_factura = ? WHERE id = ?";
    private String GETALL = "SELECT id, id_proveedor, nro_factura, fecha, hora FROM compra";
    private String GETONE = "SELECT id, id_proveedor, nro_factura, fecha, hora FROM compra WHERE id = ?";

    Connection conn;
    DAOManager manager;

    public CompraMysqlDaoImpl(Connection conn, DAOManager manager) {
        this.conn = conn;
        this.manager = manager;
    }

    @Override
    public void ingresar(Compra o) throws DAOException {
        PreparedStatement stact = null;
        ResultSet autoGenerated = null;
        try {
            stact = conn.prepareStatement(INSERT);
            stact.setLong(1, o.getIdProveedor().getId());
            stact.setString(2, o.getNroFactura());
            if (stact.executeUpdate() == 0) {
                new DAOException("Puede que no guarde la transaccion");
            }
            autoGenerated = stact.getGeneratedKeys();
            if (autoGenerated.next()) {
                o.setId(autoGenerated.getLong(1));
            } else {
                throw new DAOException("Error");
            }

        } catch (SQLException ex) {
            new DAOException("Se produjo algun error al relaizar la transaccion", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar el PreparedStatemetn", ex);
                }
            }
        }
    }

    @Override
    public void actualizar(Compra o) throws DAOException {
        PreparedStatement stact = null;

        try {
            stact = conn.prepareStatement(UPDATE);
            stact.setLong(1, o.getIdProveedor().getId());
            stact.setString(2, o.getNroFactura());
            stact.setLong(3, o.getId());
            if (stact.executeUpdate() == 0) {
                new DAOException("Error al subir datos");
            }
        } catch (SQLException ex) {
            new DAOException("Error al actualizar", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar");
                }
            }
        }
    }

    @Override
    public void eliminar(Compra o) throws DAOException {
        PreparedStatement stact = null;

        try {
            stact = conn.prepareStatement(DELETE);
            stact.setLong(1, o.getId());

            if (stact.executeUpdate() == 0) {
                new DAOException("Error al enviar query");
            }

        } catch (SQLException ex) {
            new DAOException("Error al eliminar");
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerra stact");
                }
            }
        }
    }

    @Override
    public List<Compra> getAll() throws DAOException {
        List<Compra> lista = new ArrayList<>();
        PreparedStatement stact = null;
        ResultSet rs = null;

        try {
            stact = conn.prepareStatement(GETALL);
            rs = stact.executeQuery();

            while (rs.next()) {
                Proveedor proveedor = manager.crearProveedor1().getOne(rs.getLong("id_proveedor"));
                lista.add(new Compra(rs.getLong("id"), proveedor, rs.getString("nro_factura"),
                        parseLocalDate(rs.getDate("fecha")), parseLocalTime(rs.getTime("hora"))));
            }

        } catch (SQLException ex) {
            new DAOException("Error al llamar Datos", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar estact");
                }
            }
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar rs", ex);
                }
            }
        }
        return lista;
    }

    @Override
    public Compra getOne(Long o) throws DAOException {
        Compra compra = null;
        PreparedStatement stact = null;
        ResultSet rs = null;

        try {
            stact = conn.prepareStatement(GETONE);
            stact.setLong(1, o);
            rs = stact.executeQuery();
            if (rs.next()) {
                Proveedor proveedor = manager.crearProveedor1().getOne(o);
                compra = new Compra(rs.getLong("id"), proveedor, rs.getString("nro_factura"), parseLocalDate(rs.getDate("fecha")), parseLocalTime(rs.getTime("hora")));
            }

        } catch (SQLException ex) {
            new DAOException("Error al traer el elemento", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar el stact");
                }
            }
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar rs", ex);
                }
            }
        }

        return compra;
    }

    public LocalDate parseLocalDate(Date fecha) {
        LocalDate fechaLocalDate = null;
        return fechaLocalDate = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    public LocalTime parseLocalTime(Time hora) {
        LocalTime horaLocalTime = null;
        return horaLocalTime = hora.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
    }

}
*/