/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.core.farmacia.mysql;

import com.core.farmacia.dao.DAOException;
import com.core.farmacia.dao.DAOLaboratorio;
import com.core.farmacia.model.Laboratorio;
import com.core.farmacia.model.LineaProducto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nuevo
 */
public class LaboratorioMysqlDaoImpl implements DAOLaboratorio {

    private String INSERT = "INSERT INTO laboratorio(nombre) VALUES(?)";
    private String DELETE = "DELETE FROM laboratorio WHERE id = ?";
    private String UPDATE = "UPDATE laboratorio SET nombre = ? WHERE id = ?";
    private String GETALL = "SELECT id, nombre FROM laboratorio";
    private String GETONE = "SELECT id, nombre FROM laboratorio WHERE id = ?";

    Connection conn;

    public LaboratorioMysqlDaoImpl(Connection conn) {
        this.conn = conn;
    }

    @Override
    public void ingresar(Laboratorio o) throws DAOException {
        PreparedStatement stact = null;
        ResultSet autoGenerated = null;
        try {
            stact = conn.prepareStatement(INSERT);
            stact.setString(1, o.getNombre());
            if (stact.executeUpdate() == 0) {
                new DAOException("Puede que no guarde la transaccion");
            }
            autoGenerated = stact.getGeneratedKeys();
            if (autoGenerated.next()) {
                o.setId(autoGenerated.getLong(1));
            } else {
                throw new DAOException("Error");
            }

        } catch (SQLException ex) {
            new DAOException("Se produjo algun error al relaizar la transaccion", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar el PreparedStatemetn", ex);
                }
            }
        }
    }

    @Override
    public void actualizar(Laboratorio o) throws DAOException {
        PreparedStatement stact = null;

        try {
            stact = conn.prepareStatement(UPDATE);
            stact.setString(1, o.getNombre());
            stact.setLong(2, o.getId());
            if (stact.executeUpdate() == 0) {
                new DAOException("Error al subir datos");
            }
        } catch (SQLException ex) {
            new DAOException("Error al actualizar", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar");
                }
            }
        }
    }

    @Override
    public void eliminar(Laboratorio o) throws DAOException {
        PreparedStatement stact = null;

        try {
            stact = conn.prepareStatement(DELETE);
            stact.setLong(1, o.getId());

            if (stact.executeUpdate() == 0) {
                new DAOException("Error al enviar query");
            }

        } catch (SQLException ex) {
            new DAOException("Error al eliminar");
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerra stact");
                }
            }
        }
    }

    @Override
    public List<Laboratorio> getAll() throws DAOException {
        List<Laboratorio> lista = new ArrayList<>();
        PreparedStatement stact = null;
        ResultSet rs = null;

        try {
            stact = conn.prepareStatement(GETALL);
            rs = stact.executeQuery();

            while (rs.next()) {
                lista.add(new Laboratorio(rs.getLong("id"), rs.getString("nombre")));
            }

        } catch (SQLException ex) {
            new DAOException("Error al llamar Datos", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar estact");
                }
            }
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar rs", ex);
                }
            }
        }
        return lista;
    }

    @Override
    public Laboratorio getOne(Long o) throws DAOException {
        Laboratorio laboratorio = null;
        PreparedStatement stact = null;
        ResultSet rs = null;

        try {
            stact = conn.prepareStatement(GETONE);
            stact.setLong(1, o);
            rs = stact.executeQuery();
            if (rs.next()) {
                laboratorio = new Laboratorio(rs.getLong("id"), rs.getString("nombre"));
            }

        } catch (SQLException ex) {
            new DAOException("Error al traer el elemento", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar el stact");
                }
            }
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar rs", ex);
                }
            }
        }

        return laboratorio;
    }

}
