/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.core.farmacia.mysql;

import com.core.farmacia.dao.DAOException;
import com.core.farmacia.dao.DAOPresentacion;
import com.core.farmacia.model.LineaProducto;
import com.core.farmacia.model.Presentacion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nuevo
 */
public class PresentacionMysqlDaoImpl implements DAOPresentacion {

    private String INSERT = "INSERT INTO presentacion(nombre) VALUES(?)";
    private String DELETE = "DELETE FROM presentacion WHERE id = ?";
    private String UPDATE = "UPDATE presentacion SET nombre=? WHERE id = ?";
    private String GETALL = "SELECT id, nombre FROM presentacion";
    private String GETONE = "SELECT id, nombre FROM presentacion WHERE id = ?";
    Connection conn;

    public PresentacionMysqlDaoImpl(Connection conn) {
        this.conn = conn;
    }

    @Override
    public void ingresar(Presentacion o) throws DAOException {
        PreparedStatement stact = null;
        ResultSet autoGenerated = null;
        try {
            stact = conn.prepareStatement(INSERT);
            stact.setString(1, o.getNombre());
            if (stact.executeUpdate() == 0) {
                new DAOException("Puede que no guarde la transaccion");
            }
            autoGenerated = stact.getGeneratedKeys();
            if (autoGenerated.next()) {
                o.setId(autoGenerated.getLong(1));
            } else {
                throw new DAOException("Error");
            }

        } catch (SQLException ex) {
            new DAOException("Se produjo algun error al relaizar la transaccion", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar el PreparedStatemetn", ex);
                }
            }
        }
    }

    @Override
    public void actualizar(Presentacion o) throws DAOException {
        PreparedStatement stact = null;

        try {
            stact = conn.prepareStatement(UPDATE);
            stact.setString(1, o.getNombre());
            stact.setLong(2, o.getId());
            if (stact.executeUpdate() == 0) {
                new DAOException("Error al subir datos");
            }
        } catch (SQLException ex) {
            new DAOException("Error al actualizar", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar");
                }
            }
        }
    }

    @Override
    public void eliminar(Presentacion o) throws DAOException {
        PreparedStatement stact = null;

        try {
            stact = conn.prepareStatement(DELETE);
            stact.setLong(1, o.getId());

            if (stact.executeUpdate() == 0) {
                new DAOException("Error al enviar query");
            }

        } catch (SQLException ex) {
            new DAOException("Error al eliminar");
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerra stact");
                }
            }
        }
    }

    @Override
    public List<Presentacion> getAll() throws DAOException {
        List<Presentacion> lista = new ArrayList<>();
        PreparedStatement stact = null;
        ResultSet rs = null;

        try {
            stact = conn.prepareStatement(GETALL);
            rs = stact.executeQuery();

            while (rs.next()) {
                lista.add(new Presentacion(rs.getLong("id"), rs.getString("nombre")));
            }

        } catch (SQLException ex) {
            new DAOException("Error al llamar Datos", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar estact");
                }
            }
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar rs", ex);
                }
            }
        }
        return lista;
    }

    @Override
    public Presentacion getOne(Long o) throws DAOException {
        Presentacion presentacion = null;
        PreparedStatement stact = null;
        ResultSet rs = null;

        try {
            stact = conn.prepareStatement(GETONE);
            stact.setLong(1, o);
            rs = stact.executeQuery();
            if (rs.next()) {
                presentacion = new Presentacion(rs.getLong("id"), rs.getString("nombre"));
            }

        } catch (SQLException ex) {
            new DAOException("Error al traer el elemento", ex);
        } finally {
            if (stact != null) {
                try {
                    stact.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar el stact");
                }
            }
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    new DAOException("Error al cerrar rs", ex);
                }
            }
        }

        return presentacion;
    }

}
